# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Set seed for reproducibility

In [1]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [2]:
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

#### Load data

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [7]:
X_test.shape

(10000, 28, 28)

In [8]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [9]:
y_test.shape

(10000,)

In [10]:
y_test[0]

7

#### Preprocess data

In [11]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [12]:
X_train /= 255
X_test /= 255

In [13]:
X_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [14]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [15]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

#### Design neural network architecture

In [16]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [18]:
(64*784)

50176

In [19]:
(64*784)+64

50240

In [20]:
(10*64)+10

650

#### Configure model

In [21]:
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1), metrics=['accuracy'])

#### Train!

In [22]:
model.fit(X_train, y_train, batch_size=128, epochs=100, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.4731 - acc: 0.8644 - val_loss: 0.2509 - val_acc: 0.9254
Epoch 2/100
60000/60000 [==============================] - 2s 40us/step - loss: 0.2279 - acc: 0.9337 - val_loss: 0.1903 - val_acc: 0.9427
Epoch 3/100
60000/60000 [==============================] - 2s 39us/step - loss: 0.1793 - acc: 0.9483 - val_loss: 0.1596 - val_acc: 0.9518
Epoch 4/100
60000/60000 [==============================] - 2s 33us/step - loss: 0.1481 - acc: 0.9565 - val_loss: 0.1329 - val_acc: 0.9607
Epoch 5/100
60000/60000 [==============================] - 2s 33us/step - loss: 0.1278 - acc: 0.9624 - val_loss: 0.1293 - val_acc: 0.9604
Epoch 6/100
60000/60000 [==============================] - 2s 34us/step - loss: 0.1128 - acc: 0.9669 - val_loss: 0.1162 - val_acc: 0.9637
Epoch 7/100
60000/60000 [==============================] - 2s 34us/step - loss: 0.1008 - acc: 0.9701 - val_loss: 0.1021 - 

60000/60000 [==============================] - 2s 35us/step - loss: 0.0022 - acc: 1.0000 - val_loss: 0.1045 - val_acc: 0.9768
Epoch 60/100
60000/60000 [==============================] - 2s 38us/step - loss: 0.0021 - acc: 1.0000 - val_loss: 0.1044 - val_acc: 0.9768
Epoch 61/100
60000/60000 [==============================] - 2s 40us/step - loss: 0.0020 - acc: 1.0000 - val_loss: 0.1043 - val_acc: 0.9774
Epoch 62/100
60000/60000 [==============================] - 2s 37us/step - loss: 0.0020 - acc: 1.0000 - val_loss: 0.1052 - val_acc: 0.9766
Epoch 63/100
60000/60000 [==============================] - 2s 35us/step - loss: 0.0019 - acc: 1.0000 - val_loss: 0.1046 - val_acc: 0.9774
Epoch 64/100
60000/60000 [==============================] - 2s 36us/step - loss: 0.0018 - acc: 1.0000 - val_loss: 0.1065 - val_acc: 0.9766
Epoch 65/100
60000/60000 [==============================] - 3s 45us/step - loss: 0.0018 - acc: 1.0000 - val_loss: 0.1067 - val_acc: 0.9762
Epoch 66/100
60000/60000 [==============

In [23]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 36us/step


[0.11817656577845391, 0.977]