In [1]:
import numpy as np
np.random.seed(42)

In [2]:
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [3]:
(X_train,Y_train),(X_test,Y_test)=mnist.load_data()

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
Y_train.shape

(60000,)

In [6]:
X_train[0]
Y_train[0:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [7]:
X_train1=X_train.reshape(60000,784).astype('float32')
X_test1=X_test.reshape(10000,784).astype('float32')

In [8]:
X_train1=X_train1/255
X_test1=X_test1/255

In [9]:
X_train1[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [10]:
classes=10
Y_train=keras.utils.to_categorical(Y_train,classes)
Y_test=keras.utils.to_categorical(Y_test,classes)

In [11]:
Y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [12]:
model = Sequential()
model.add(Dense((64),activation='sigmoid',input_shape=(784,)))
model.add(Dense((10),activation='softmax'))

In [13]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss='mean_squared_error',optimizer=SGD(lr=0.01),metrics=['accuracy'])

In [16]:
model.fit(X_train1,Y_train,batch_size=128,epochs=250,verbose=1,validation_data=(X_test1,Y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/250
60000/60000 [==============================] - 3s 55us/step - loss: 0.0934 - acc: 0.1147 - val_loss: 0.0927 - val_acc: 0.1277
Epoch 2/250
60000/60000 [==============================] - 2s 26us/step - loss: 0.0923 - acc: 0.1302 - val_loss: 0.0918 - val_acc: 0.1433
Epoch 3/250
60000/60000 [==============================] - 1s 21us/step - loss: 0.0915 - acc: 0.1445 - val_loss: 0.0911 - val_acc: 0.1559
Epoch 4/250
60000/60000 [==============================] - 2s 26us/step - loss: 0.0908 - acc: 0.1552 - val_loss: 0.0905 - val_acc: 0.1657
Epoch 5/250
60000/60000 [==============================] - 1s 22us/step - loss: 0.0903 - acc: 0.1642 - val_loss: 0.0900 - val_acc: 0.1738
Epoch 6/250
60000/60000 [==============================] - 1s 25us/step - loss: 0.0899 - acc: 0.1694 - val_loss: 0.0896 - val_acc: 0.1764
Epoch 7/250
60000/60000 [==============================] - 1s 25us/step - loss: 0.0894 - acc: 0.1769 - val_loss: 0.0892 - 

60000/60000 [==============================] - 1s 23us/step - loss: 0.0678 - acc: 0.6190 - val_loss: 0.0672 - val_acc: 0.6239
Epoch 60/250
60000/60000 [==============================] - 1s 24us/step - loss: 0.0673 - acc: 0.6219 - val_loss: 0.0666 - val_acc: 0.6265
Epoch 61/250
60000/60000 [==============================] - 1s 24us/step - loss: 0.0667 - acc: 0.6253 - val_loss: 0.0661 - val_acc: 0.6292
Epoch 62/250
60000/60000 [==============================] - 2s 27us/step - loss: 0.0662 - acc: 0.6285 - val_loss: 0.0656 - val_acc: 0.6324
Epoch 63/250
60000/60000 [==============================] - 1s 24us/step - loss: 0.0657 - acc: 0.6320 - val_loss: 0.0650 - val_acc: 0.6348
Epoch 64/250
60000/60000 [==============================] - 1s 21us/step - loss: 0.0651 - acc: 0.6351 - val_loss: 0.0645 - val_acc: 0.6388
Epoch 65/250
60000/60000 [==============================] - 1s 21us/step - loss: 0.0646 - acc: 0.6380 - val_loss: 0.0639 - val_acc: 0.6420
Epoch 66/250
60000/60000 [==============

Epoch 118/250
60000/60000 [==============================] - 1s 24us/step - loss: 0.0424 - acc: 0.7846 - val_loss: 0.0415 - val_acc: 0.7965
Epoch 119/250
60000/60000 [==============================] - 1s 24us/step - loss: 0.0421 - acc: 0.7874 - val_loss: 0.0412 - val_acc: 0.7982
Epoch 120/250
60000/60000 [==============================] - 2s 26us/step - loss: 0.0418 - acc: 0.7897 - val_loss: 0.0409 - val_acc: 0.8007
Epoch 121/250
60000/60000 [==============================] - 2s 27us/step - loss: 0.0415 - acc: 0.7922 - val_loss: 0.0406 - val_acc: 0.8029
Epoch 122/250
60000/60000 [==============================] - 1s 23us/step - loss: 0.0412 - acc: 0.7948 - val_loss: 0.0403 - val_acc: 0.8051
Epoch 123/250
60000/60000 [==============================] - 1s 22us/step - loss: 0.0409 - acc: 0.7966 - val_loss: 0.0400 - val_acc: 0.8069
Epoch 124/250
60000/60000 [==============================] - 2s 25us/step - loss: 0.0406 - acc: 0.7988 - val_loss: 0.0397 - val_acc: 0.8087
Epoch 125/250
60000/

60000/60000 [==============================] - 1s 20us/step - loss: 0.0304 - acc: 0.8521 - val_loss: 0.0294 - val_acc: 0.8594
Epoch 177/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0302 - acc: 0.8526 - val_loss: 0.0293 - val_acc: 0.8597
Epoch 178/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0301 - acc: 0.8531 - val_loss: 0.0291 - val_acc: 0.8600
Epoch 179/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0300 - acc: 0.8534 - val_loss: 0.0290 - val_acc: 0.8609
Epoch 180/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0298 - acc: 0.8538 - val_loss: 0.0289 - val_acc: 0.8616
Epoch 181/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0297 - acc: 0.8543 - val_loss: 0.0287 - val_acc: 0.8621
Epoch 182/250
60000/60000 [==============================] - 1s 23us/step - loss: 0.0296 - acc: 0.8547 - val_loss: 0.0286 - val_acc: 0.8624
Epoch 183/250
60000/60000 [=======

60000/60000 [==============================] - 1s 20us/step - loss: 0.0247 - acc: 0.8703 - val_loss: 0.0237 - val_acc: 0.8813
Epoch 235/250
60000/60000 [==============================] - 1s 22us/step - loss: 0.0246 - acc: 0.8706 - val_loss: 0.0236 - val_acc: 0.8815
Epoch 236/250
60000/60000 [==============================] - 1s 22us/step - loss: 0.0245 - acc: 0.8708 - val_loss: 0.0235 - val_acc: 0.8816
Epoch 237/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0245 - acc: 0.8712 - val_loss: 0.0235 - val_acc: 0.8818
Epoch 238/250
60000/60000 [==============================] - 1s 21us/step - loss: 0.0244 - acc: 0.8715 - val_loss: 0.0234 - val_acc: 0.8822
Epoch 239/250
60000/60000 [==============================] - 1s 20us/step - loss: 0.0243 - acc: 0.8717 - val_loss: 0.0233 - val_acc: 0.8823
Epoch 240/250
60000/60000 [==============================] - 1s 21us/step - loss: 0.0243 - acc: 0.8720 - val_loss: 0.0233 - val_acc: 0.8824
Epoch 241/250
60000/60000 [=======

In [20]:
score = model.evaluate(X_test1, Y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.02265689996778965
Test accuracy: 0.8835
